# Generated by Django 4.2.16 on 2024-11-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_lector',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
