# Generated by Django 4.2.16 on 2024-11-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Lector', 'Lector'), ('Student', 'Student')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
