# Generated by Django 4.2.16 on 2024-11-26 19:38

import UniversityApp.validators.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_biography_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(help_text='This field is required!', max_length=15, validators=[django.core.validators.MinLengthValidator(2), UniversityApp.validators.validators.AlphabeticValidator()]),
        ),
    ]
