# Generated by Django 4.2.16 on 2024-12-02 14:17

import UniversityApp.validators.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_password_alter_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), UniversityApp.validators.validators.AlphabeticValidator(), UniversityApp.validators.validators.CapitalizedValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2), UniversityApp.validators.validators.AlphabeticValidator(), UniversityApp.validators.validators.CapitalizedValidator()]),
        ),
    ]
