# Generated by Django 4.2.16 on 2024-12-04 16:13

import UniversityApp.validators.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0013_alter_course_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This field is required.', max_length=50, validators=[django.core.validators.MinLengthValidator(2),])),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('readme', models.CharField(help_text="Enter lesson's main points, separated with comma.", max_length=150)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
        ),
    ]
