# Generated by Django 4.2.16 on 2024-11-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('category', models.CharField(choices=[('WD', 'Web Design'), ('GD', 'Graphic Design'), ('VE', 'Video Editing'), ('OM', 'Online Marketing'), ('SD', 'Software Development'), ('OTH', 'Other')], default='OTH', max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.URLField(default='http://localhost:8000/static/img/course.jpg')),
            ],
        ),
    ]
