# Generated by Django 4.2.16 on 2024-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.URLField(blank=True, default='http://localhost:8000/static/img/course.jpg', null=True),
        ),
    ]
