# Generated by Django 4.2.16 on 2024-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Web Design', 'Web Design'), ('Graphic Design', 'Graphic Design'), ('Video Editing', 'Video Editing'), ('Online Marketing', 'Online Marketing'), ('Software Development', 'Software Development'), ('Other', 'Other')], max_length=40),
        ),
    ]
