# Generated by Django 4.2.16 on 2024-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Web Design', 'Web Design'), ('Graphic Design', 'Graphic Design'), ('Video Editing', 'Video Editing'), ('Online Marketing', 'Online Marketing')], help_text='This field is required!', max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='This field is required!', max_length=70, unique=True),
        ),
    ]
