# Generated by Django 4.2.16 on 2024-11-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_category_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lector',
            field=models.CharField(max_length=40, null=True, blank=True),
        ),
    ]
