# Generated by Django 4.2.16 on 2024-11-29 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_category_alter_course_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 11, 29), help_text='Course starting date: This field is required!'),
        ),
    ]
